# AI-HR FastAPI Dockerfile
FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# System deps
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Copy sources
COPY . /app

# Install deps
RUN pip install  --upgrade pip \
    && pip install -r requirements.txt

RUN pip install pymongo

EXPOSE 8002

ENV OPENROUTER_API_KEY=""

CMD ["python", "api.py"]
